"""Original supplemental briefs and question seeds, not Armstrong assignments.

Each row contains: core knowledge, two concrete problems with reasoning keys,
and an incorrect claim with its repair. No row represents learner evidence.
"""
CONTENT = {}


def add(key, core, prompt, answer, transfer, transfer_answer, claim, repair):
    CONTENT[key] = dict(core=core, prompt=prompt, answer=answer, transfer=transfer,
                        transferAnswer=transfer_answer, claim=claim, repair=repair)


add('u1-numerical-limits',
    r'A limit concerns nearby inputs, not the value at the point. Tables provide evidence for a conjecture, not a proof; rounding and sparse sampling can hide behavior.',
    r'For $f(x)=(x^2-4)/(x-2)$, calculate $f(1.9),f(1.99),f(2.01),f(2.1)$. What limit do the samples suggest?',
    r'$3.9,3.99,4.01,4.1$, suggesting 4. For $x\ne2$, factoring gives $f(x)=x+2$; the table alone is not proof.',
    r'A table reports $f(0.1)=f(0.01)=f(0.001)=1$. Can it prove the two-sided limit at zero equals 1? Name two missing checks.',
    r'No. Left-hand behavior and unobserved closer inputs remain unchecked; finite sampling cannot prove convergence.',
    r'If all displayed values round to 1, the exact limit must be 1.',
    r'Rounded samples do not control all sufficiently close inputs; require analytic bounds or an appropriate theorem.')
add('u1-graphical-limits',
    r'Read the height approached along each branch. An open circle describes a missing endpoint; a filled point describes the assigned value.',
    r'A graph approaches height 3 from both sides of $x=2$, has an open circle at $(2,3)$ and a filled point at $(2,7)$. State both one-sided limits, the two-sided limit and $f(2)$.',
    r'Both one-sided limits and the two-sided limit are 3; $f(2)=7$. Nearby branch heights determine the limits.',
    r'Change the right branch to approach height 5, retaining $f(2)=7$. Which requested quantities change?',
    r'The right limit becomes 5 and the two-sided limit no longer exists; the left limit remains 3 and the point value remains 7.',
    r'The filled point always determines the limit.',
    r'A single point does not determine nearby behavior; trace each branch instead.')
add('u1-one-two-sided-limits',
    r'A finite two-sided limit exists exactly when the two finite one-sided limits agree. Domain endpoints require an explicit one-sided convention.',
    r'Let $f(x)=x+1$ for $x<0$ and $f(x)=2x+3$ for $x>0$. Find the one-sided limits at zero and decide whether a two-sided limit exists.',
    r'Left 1, right 3; no two-sided limit because they disagree.',
    r'Replace the right branch by $2x+k$. Choose $k$ so the two-sided limit exists, without defining $f(0)$.',
    r'$k=1$. Both sides approach 1; the point value is irrelevant to this limit.',
    r'A two-sided limit is the average of the left and right limits.',
    r'It requires agreement, not averaging; a jump cannot be repaired by taking a midpoint.')
add('u1-graphical-limits-of-compositions-of-functions',
    r'Track the side from which inner outputs approach the outer input. A discontinuous outer function prevents blind use of the composition-limit theorem.',
    r'Let $g(x)=x^2$ and let $f(u)=1$ for $u>0$, $f(0)=9$, and $f(u)=-1$ for $u<0$. Find $\lim_{x\to0}f(g(x))$ and $f(g(0))$.',
    r'The limit is 1 since $x^2>0$ for $x\ne0$; the point value is 9.',
    r'With the same $f$, replace $g(x)$ by $x$. Find the left and right limits of the composition at zero.',
    r'Left -1, right 1; the two-sided limit does not exist because the inner output crosses the outer jump.',
    r'Whenever $g(x)\to0$, $f(g(x))\to f(0)$.',
    r'That conclusion needs appropriate outer continuity. The first problem is a counterexample with limit 1 but $f(0)=9$.')
add('u1-properties-and-linearity-of-limits',
    r'Finite limits respect sums, constant multiples and products. The quotient law additionally requires a nonzero denominator limit.',
    r'If $f(x)\to2$ and $g(x)\to-3$ as $x\to a$, find $\lim(4f(x)-g(x)^2)$. Identify the laws used.',
    r'$8-9=-1$ by constant multiple, product/power and difference laws.',
    r'Under the same assumptions, find $\lim[f(x)/(g(x)+3)]$ if possible from the given information.',
    r'Not determined: the denominator approaches zero. For example $g=-3+(x-a)$ gives opposing infinite sides, while $g=-3+(x-a)^2$ gives positive infinite behavior when $f=2$.',
    r'A denominator approaching zero means the quotient limit is zero.',
    r'The quotient law does not apply. Analyze the expression and signs; zero denominator alone determines no quotient limit.')
add('u1-analytic-limits-of-analytic-functions',
    r'Check the original domain and substitution first. Factoring, conjugates and common denominators create equal expressions on a punctured neighborhood.',
    r'Evaluate $\lim_{x\to3}(x^2-9)/(x-3)$ and justify cancellation.',
    r'6. For $x\ne3$, the numerator factors as $(x-3)(x+3)$; the equal nearby expression tends to 6.',
    r'Evaluate $\lim_{x\to0}(\sqrt{4+x}-2)/x$ without L’Hôpital.',
    r'$1/4$. Rationalization gives $1/(\sqrt{4+x}+2)$ for nearby nonzero $x$.',
    r'You can cancel $x$ from $(x+2)/(x+3)$ to obtain $2/3$.',
    r'Only common factors cancel, not terms inside sums; at $x=1$ the original is $3/4$.')
add('u1-limits-involving-infinity',
    r'An infinite limit describes unbounded output, not a real value. Determine signs on each side of a denominator zero.',
    r'Find both one-sided limits of $1/(x-2)$ at $x=2$.',
    r'Left $-\infty$, right $+\infty$, since the denominator has opposite signs.',
    r'Repeat for $1/(x-2)^2$. What changed?',
    r'Both sides approach $+\infty$ because the squared denominator is positive and tends to zero.',
    r'Every undefined rational expression has an infinite limit.',
    r'False: $(x^2-4)/(x-2)$ is undefined at 2 but has finite limit 4.')
add('u1-limits-of-rational-functions-at-infinity',
    r'Divide by the leading denominator power to justify degree comparisons. Analyze signs separately at positive and negative infinity.',
    r'Find $\lim_{x\to\infty}(3x^2-x)/(2x^2+7)$ and explain which terms vanish.',
    r'$3/2$. Divide numerator and denominator by $x^2$; $1/x$ and $7/x^2$ tend to zero.',
    r'Find the limits of $(2x^3+1)/(x^2+1)$ at both ends of the real line.',
    r'$+\infty$ on the right and $-\infty$ on the left; the expression grows like $2x$.',
    r'A higher numerator degree always gives $+\infty$ at both ends.',
    r'Parity and leading coefficient signs matter; the odd leading behavior $2x$ has opposite end signs.')
add('u1-asymptotic-comparison',
    r'Compare dominant growth through a ratio, then check the direction and signs. Ratios tending to 1 express relative agreement, not necessarily small absolute difference.',
    r'As $x\to\infty$, compare $p(x)=x^2+3x$ with $q(x)=x^2$ by computing $p/q$. Does $p-q$ tend to zero?',
    r'$p/q=1+3/x\to1$, but $p-q=3x\to\infty$. Relative agreement differs from absolute agreement.',
    r'Find $\lim_{x\to\infty}(\sqrt{9x^2+x}-3x)$ without L’Hôpital.',
    r'$1/6$. Rationalize to $x/(\sqrt{9x^2+x}+3x)$, then divide by positive $x$.',
    r'If $p/q\to1$, then $p-q\to0$.',
    r'The first problem disproves this. A ratio controls relative error, not absolute difference.')
add('u1-limit-definition-of-asymptotes',
    r'Horizontal asymptotes come from limits at infinity; vertical asymptotes come from unbounded one-sided behavior at finite inputs. Holes are different.',
    r'Find the horizontal and vertical asymptotes of $f(x)=(2x+1)/(x-3)$, stating the limits that establish them.',
    r'$y=2$ at both ends. $x=3$ is vertical: numerator tends to 7, so left limit $-\infty$ and right $+\infty$.',
    r'Does $(x^2-9)/(x-3)$ have a vertical asymptote at 3? Explain using a limit.',
    r'No: its limit is 6. The missing input creates a removable hole, not unbounded behavior.',
    r'A graph can never cross a horizontal asymptote.',
    r'Horizontal asymptotes constrain end behavior, not finite points. $2+x/(x^2+1)$ crosses $y=2$ at zero.')
add('u1-limits-involving-indeterminate-forms',
    r'$0/0$, $\infty/\infty$ and $\infty-\infty$ signal insufficient information. They are forms, not evaluated answers.',
    r'Compare $\lim_{x\to0}x/x$ with $\lim_{x\to0}x^2/x$. Both substitute to $0/0$; find each limit.',
    r'1 and 0 respectively, because the nearby expressions equal 1 and $x$.',
    r'Find $\lim_{x\to\infty}(\sqrt{x^2+4x}-x)$ using a conjugate.',
    r'2. Rationalize to $4x/(\sqrt{x^2+4x}+x)$ and divide by positive $x$.',
    r'$\infty-\infty=0$, so no further work is needed.',
    r'Unbounded quantities can differ by a finite nonzero amount or diverge; the displayed radical example tends to 2.')
add('u1-limits-involving-transcendental-functions',
    r'Use continuity on the actual domain for exponential, logarithmic and trigonometric limits. Radians are required for standard trigonometric limits.',
    r'Evaluate $\lim_{x\to0}(e^x+\cos x)$ and name the justification.',
    r'2 by continuity of both functions and the sum law.',
    r'Compare $\lim_{x\to0^+}\ln x$ and $\lim_{x\to1}\ln x$. State the domain issue.',
    r'$-\infty$ and 0. The real logarithm is defined only for positive inputs; zero is a boundary, not an allowed substitution point.',
    r'Continuity permits substituting any real input into $\ln x$.',
    r'Continuity is within its domain $(0,\infty)$; negative or zero real logarithm inputs are invalid.')
add('u1-sandwich-theorem',
    r'If lower and upper bounds hold near the approach point and both tend to the same finite value, the bounded middle function has that limit.',
    r'Prove $\lim_{x\to0}x^2\sin(1/x)=0$ using explicit bounds.',
    r'$-x^2\le x^2\sin(1/x)\le x^2$ for $x\ne0$; both bounds tend to zero.',
    r'Given $2-x^2\le h(x)\le2+x^2$ for $0<|x|<1$, determine $\lim_{x\to0}h(x)$. Is $h(0)$ determined?',
    r'The limit is 2 by matching bounds; the value at zero is not specified.',
    r'Any two bounds prove a limit, even if their limits differ.',
    r'The bound limits must agree. Bounds -1 and 1 allow both a constant and an oscillating function.')
add('u1-special-trigonometric-limits',
    r'In radians, $\sin u/u\to1$ as $u\to0$. Rescale the argument carefully; use identities to transform cosine differences.',
    r'Find $\lim_{x\to0}\sin(5x)/(2x)$ without L’Hôpital.',
    r'$5/2$: rewrite as $(5/2)\sin(5x)/(5x)$.',
    r'Find $\lim_{x\to0}(1-\cos x)/x^2$ using a trigonometric identity.',
    r'$1/2$. Since $1-\cos x=2\sin^2(x/2)$, the expression is $\tfrac12[\sin(x/2)/(x/2)]^2$.',
    r'$\sin(5x)/x\to1$ because every sine-over-input limit is 1.',
    r'The denominator must match the sine argument; the missing scale makes this limit 5.')
add('u1-limits-involving-piecewise-functions-and-absolute-value',
    r'Choose each branch using the approaching side, not the point value. Resolve absolute values through the sign of their argument.',
    r'Find both one-sided limits of $|x|/x$ at zero.',
    r'Left -1 and right 1, so there is no two-sided limit.',
    r'Let $f(x)=kx+2$ for $x<1$ and $f(x)=x^2+4$ for $x>1$. Choose $k$ for a two-sided limit at 1.',
    r'$k=3$: the left limit $k+2$ must equal the right limit 5.',
    r'You can replace $|x|$ with $x$ on both sides of zero.',
    r'For negative inputs $|x|=-x$, which changes the left branch and its limiting value.')
add('u1-graphical-continuity-and-discontinuities',
    r'Continuity at an interior point requires a defined value, an existing finite two-sided limit and equality between them. Distinguish holes, jumps and unbounded discontinuities.',
    r'A graph approaches $(1,4)$ from both sides but has a filled point at $(1,6)$. Is it continuous at 1? What one-point change repairs it?',
    r'No, because limit 4 differs from value 6. Assign $f(1)=4$ to repair the removable discontinuity.',
    r'If the left branch approaches 4 and the right approaches 7, can changing only $f(1)$ make the function continuous?',
    r'No: the two-sided limit fails, so no point value repairs the jump.',
    r'A defined point value guarantees continuity.',
    r'Nearby branch limits must also exist and equal that value; the first graph has a defined but discontinuous point.')
add('u1-analytic-continuity-and-discontinuities',
    r'At a piecewise join, separately match the left limit, right limit and assigned value. Rational expressions are continuous wherever their denominator is nonzero.',
    r'Let $f(x)=(x^2-1)/(x-1)$ for $x\ne1$ and $f(1)=k$. Choose $k$ for continuity.',
    r'$k=2$. The nearby expression is $x+1$, so its two-sided limit must match the assigned value.',
    r'Let $g(x)=ax+1$ for $x<2$ and $g(x)=x^2$ for $x\ge2$. Choose $a$ for continuity at 2.',
    r'$a=3/2$: $2a+1=4=g(2)$, matching both sides.',
    r'Cancelling a factor automatically defines the original function at its missing input.',
    r'Cancellation describes equality only where the factor is nonzero. A separate point assignment is needed to extend the domain.')
add('u1-intermediate-value-theorem-ivt',
    r'For a continuous function on a closed interval, every value between its endpoint outputs occurs somewhere on that interval. Opposite endpoint signs guarantee at least one root, not uniqueness.',
    r'Use IVT to show $x^3+x-1=0$ has a root in $(0,1)$. State every hypothesis.',
    r'The polynomial is continuous on $[0,1]$; its endpoint values are -1 and 1. Zero lies strictly between them, so a root lies inside.',
    r'Let $f(x)=-1$ for $x<0$ and $f(x)=1$ for $x\ge0$ on $[-1,1]$. Explain why opposite endpoint signs do not yield a root here.',
    r'The function jumps at zero and is not continuous on the interval. IVT’s continuity hypothesis fails.',
    r'IVT proves there is exactly one root.',
    r'IVT establishes existence. For example $x(x^2-1)$ on $[-2,2]$ changes endpoint sign but has three roots.')
add('u1-continuity-theorems',
    r'Sums, products and compositions preserve continuity under their hypotheses. A quotient requires a nonzero denominator; continuity of a composition requires valid inner and outer domains.',
    r'On which real inputs is $h(x)=\ln(x-1)/(x-3)$ continuous? Explain both exclusions.',
    r'On $(1,3)\cup(3,\infty)$: logarithm requires $x>1$, and the denominator excludes 3.',
    r'Is $\sqrt{4-x^2}$ continuous on its real domain? State endpoint continuity conventions.',
    r'Yes on $[-2,2]$; the polynomial and square root are continuous on valid inputs. At endpoints use relative-domain/one-sided continuity.',
    r'Composing two continuous functions makes a function continuous on every real input.',
    r'The composition must be defined. $\ln(x-1)$ is not a real function at $x\le1$.')

add('u2-limit-definition-of-the-derivative',
    r'$f^{\prime}(a)=\lim_{h\to0}[f(a+h)-f(a)]/h$ when the finite two-sided limit exists. The quotient is a secant slope before taking its limit.',
    r'Use the limit definition, not the power rule, to find the derivative of $f(x)=x^2+3$ at $x=2$.',
    r'The quotient is $[(2+h)^2+3-7]/h=4+h$ for nonzero $h$, tending to 4.',
    r'Use the difference quotient to decide whether $f(x)=|x-1|$ is differentiable at 1.',
    r'The quotient $|h|/h$ is -1 on the left and 1 on the right, so no finite two-sided derivative exists.',
    r'Set $h=0$ in the difference quotient before simplifying.',
    r'The quotient is undefined at zero; simplify for nonzero increments and then take the limit.')
add('u2-tangent-lines-and-instantaneous-rate-of-change',
    r'A tangent line through $(a,f(a))$ has slope $f^{\prime}(a)$; an instantaneous rate is the limit of signed average rates, with output-per-input units.',
    r'Find the tangent line to $f(x)=x^2+1$ at $x=2$.',
    r'$y-5=4(x-2)$ because the point is $(2,5)$ and the derivative there is 4.',
    r'Position is $s(t)=t^2+2t$ meters, with time in seconds. Compare average velocity on $[1,3]$ with instantaneous velocity at $t=1$.',
    r'Average $(15-3)/2=6$ m/s; instantaneous $s^{\prime}(1)=4$ m/s. They measure interval versus local change.',
    r'The tangent slope equals $f(a)/a$.',
    r'That is a slope from the origin when defined, not generally the local derivative; at 2 it gives $5/2$ rather than 4.')
add('u2-derivative-notation',
    r'$f^{\prime}(x)$, $dy/dx$ and $D_x f$ denote differentiation with respect to the named variable. Distinguish the derivative function from its evaluated value and its units.',
    r'For $s(t)=3t^2$, write the derivative function and its value at $t=2$, using prime and Leibniz notation.',
    r'$s^{\prime}(t)=ds/dt=6t$; $s^{\prime}(2)=12$. If position is meters and time seconds, the value is 12 m/s.',
    r'If $r$ depends on $t$ and $A=\pi r^2$, explain the difference between $dA/dr$ and $dA/dt$.',
    r'$dA/dr=2\pi r$ measures area change per radius; $dA/dt=2\pi r\,dr/dt$ measures change per time.',
    r'$f^{\prime}(2)$ and $f^{\prime}(x)$ are interchangeable expressions.',
    r'One is an evaluated number and the other a function of its input; evaluation requires substituting into the derivative.')
add('u2-linearity-of-differentiation',
    r'Differentiation distributes over finite sums and constant multiples of differentiable functions. A variable coefficient is not a constant multiple.',
    r'If $f^{\prime}(2)=3$ and $g^{\prime}(2)=-4$, find $h^{\prime}(2)$ for $h=5f-2g+7$.',
    r'$5(3)-2(-4)=23$; the derivative of the constant 7 is zero.',
    r'Given $f(2)=5$ and $f^{\prime}(2)=3$, find the derivative of $xf(x)$ at 2. Explain why linearity alone is insufficient.',
    r'$f(2)+2f^{\prime}(2)=11$ by the product rule. The coefficient $x$ changes with the differentiation variable.',
    r'$D_x[xf(x)]=x f^{\prime}(x)$ because multiples differentiate linearly.',
    r'Only constant multiples permit that rule; the derivative of $x$ contributes the additional $f(x)$ term.')
add('u2-power-rule-for-derivatives',
    r'$D_x x^n=nx^{n-1}$ on intervals where the real power is defined and differentiable. The constant case and negative/fractional powers require domain attention.',
    r'Differentiate $3x^4-2x^{-2}+5$ and state its domain.',
    r'$12x^3+4x^{-3}$ for $x\ne0$; rewrite powers and apply linearity.',
    r'Differentiate $\sqrt{x}$ for $x>0$. What happens to the right difference quotient at zero?',
    r'$1/(2\sqrt{x})$ on positive inputs; at zero the quotient $\sqrt{h}/h=1/\sqrt{h}$ is unbounded as $h\to0^+$. No finite derivative there.',
    r'The power rule makes every fractional power differentiable at zero.',
    r'The real domain and finite derivative must be checked; the square-root endpoint is a counterexample.')
add('u2-product-rule-for-derivatives',
    r'$(fg)^{\prime}=f^{\prime} g+fg^{\prime}$. Both factors change, so one factor is held while the other differentiates in each term.',
    r'Differentiate $(x^2+1)(x^3-2)$ using the product rule and check by expanding.',
    r'$2x(x^3-2)+3x^2(x^2+1)=5x^4+3x^2-4x$; expansion gives $x^5+x^3-2x^2-2$.',
    r'If $f(1)=2,f^{\prime}(1)=3,g(1)=-1,g^{\prime}(1)=4$, find $(fg)^{\prime}(1)$.',
    r'$3(-1)+2(4)=5$. Values of the undifferentiated factors are essential.',
    r'$(fg)^{\prime}=f^{\prime} g^{\prime}$.',
    r'For $f=g=x$, this predicts 1 instead of the true derivative $2x$.')
add('u2-quotient-rule-for-derivatives',
    r'$(f/g)^{\prime}=(gf^{\prime}-fg^{\prime})/g^2$ where $g\ne0$. Preserve subtraction order and the original domain.',
    r'Differentiate $(x^2+1)/(x-1)$ and state excluded inputs.',
    r'$(x^2-2x-1)/(x-1)^2$ for $x\ne1$, from $[(x-1)2x-(x^2+1)]/(x-1)^2$.',
    r'If $f(0)=2,f^{\prime}(0)=1,g(0)=4,g^{\prime}(0)=-3$, find $(f/g)^{\prime}(0)$.',
    r'$[4(1)-2(-3)]/16=5/8$.',
    r'$(f/g)^{\prime}=f^{\prime}/g^{\prime}$.',
    r'For $f=x^2,g=x$ on $x\ne0$, the quotient equals $x$ and has derivative 1, while the proposed rule gives $2x$.')
add('u2-chain-rule',
    r'$(f\circ g)^{\prime}(x)=f^{\prime}(g(x))g^{\prime}(x)$; evaluate the outer derivative at the inner output. For nesting, include every layer.',
    r'Differentiate $y=(3x^2+1)^4$, naming the inner and outer functions.',
    r'$24x(3x^2+1)^3$. Outer derivative $4u^3$ is evaluated at $u=3x^2+1$ and multiplied by $6x$.',
    r'Given $g(2)=5,g^{\prime}(2)=-3,f^{\prime}(5)=4,f^{\prime}(2)=9$, find $(f\circ g)^{\prime}(2)$ and justify which table entry is used.',
    r'$4(-3)=-12$; use $f^{\prime}(5)$ because the outer input is $g(2)=5$.',
    r'The chain rule uses $f^{\prime}(x)g^{\prime}(x)$ at the original input.',
    r'The outer derivative is evaluated at $g(x)$, not necessarily $x$; the table problem shows the difference.')
add('u2-implicit-differentiation',
    r'Treat $y$ as a function of $x$: differentiating a $y$ expression introduces $dy/dx$. Solving for a finite slope may fail where its coefficient vanishes.',
    r'For $x^2+y^2=25$, find $dy/dx$ and its value at $(3,4)$.',
    r'$2x+2y y^{\prime}=0$, so $y^{\prime}=-x/y$ when $y\ne0$; at $(3,4)$ the slope is $-3/4$.',
    r'For $xy+y^2=6$, find the tangent slope at $(1,2)$.',
    r'$y+(x+2y)y^{\prime}=0$, so at the specified point $y^{\prime}=-2/5$. Check $1(2)+4=6$.',
    r'Differentiating $y^2$ with respect to $x$ gives $2y$.',
    r'It gives $2y\,dy/dx$ by the chain rule; the changing dependent variable cannot be treated as the input itself.')
add('u2-derivatives-of-inverse-functions',
    r'If $f(a)=b$ and an appropriate differentiable inverse exists with $f^{\prime}(a)\ne0$, then $(f^{-1})^{\prime}(b)=1/f^{\prime}(a)$. An inverse is not a reciprocal.',
    r'A differentiable one-to-one function has $f(2)=7$ and $f^{\prime}(2)=4$. Find $(f^{-1})^{\prime}(7)$.',
    r'$1/4$. Differentiate $f(f^{-1}(x))=x$ and evaluate at the corresponding inverse input.',
    r'For $f(x)=x^3$, compare the inverse derivative at 8 with what happens at zero.',
    r'At 8 it is $1/f^{\prime}(2)=1/12$. The cube-root inverse has no finite derivative at zero, where $f^{\prime}(0)=0$.',
    r'$f^{-1}(x)=1/f(x)$.',
    r'The inverse undoes input/output mapping; for $f=x^3$, the inverse is $\sqrt[3]{x}$, not $x^{-3}$.')
add('u2-higher-order-derivatives',
    r'Each higher derivative differentiates the preceding derivative. For a time-based position, velocity and acceleration are first and second derivatives, with changing units.',
    r'Find $f^{\prime},f^{\prime\prime},f^{\prime\prime\prime}$ for $f(x)=x^4-2x^2$.',
    r'$4x^3-4x$, $12x^2-4$, $24x$ respectively.',
    r'If $s(t)=t^3-3t$ meters, find velocity and acceleration at $t=2$ with units.',
    r'$v=3t^2-3$, so 9 m/s; $a=6t$, so 12 m/s².',
    r'$f^{\prime\prime}$ means $(f^{\prime})^2$.',
    r'It means differentiating again, not squaring; for $f=x^2$, $f^{\prime\prime}=2$ while $(f^{\prime})^2=4x^2$.')
add('u2-derivatives-of-exponential-and-logarithmic-functions',
    r'$D_x e^{u}=e^{u}u^{\prime}$, $D_x\ln|u|=u^{\prime}/u$ for $u\ne0$; $D_x a^x=a^x\ln a$ for $a>0$. Preserve real log domains.',
    r'Differentiate $e^{3x}+\ln x$ and state the domain.',
    r'$3e^{3x}+1/x$ for $x>0$.',
    r'Differentiate $\ln(x^2+1)+2^x$. Explain the chain rule and base factor.',
    r'$2x/(x^2+1)+2^x\ln2$ on all real inputs.',
    r'The derivative of $a^x$ is $xa^{x-1}$.',
    r'The power rule applies to a variable base with fixed exponent. For a constant positive base the correct derivative is $a^x\ln a$.')
add('u2-derivatives-of-sine-and-cosine',
    r'In radians, $D_x\sin u=\cos u\,u^{\prime}$ and $D_x\cos u=-\sin u\,u^{\prime}$. Track the sign and inner derivative.',
    r'Differentiate $\sin(2x)+\cos(x^2)$.',
    r'$2\cos(2x)-2x\sin(x^2)$, using each inner derivative.',
    r'For $f(x)=\cos(3x)$, find $f^{\prime}(\pi/6)$ and interpret the sign.',
    r'$f^{\prime}=-3\sin(3x)$, so the slope is -3 at $\pi/6$; the function is locally decreasing.',
    r'The derivative of cosine is positive sine.',
    r'It is negative sine in radians; at $\pi/2$ cosine is decreasing with slope -1.')
add('u2-derivatives-of-more-trigonometric-functions',
    r'$D\tan x=\sec^2x$, $D\sec x=\sec x\tan x$, $D\cot x=-\csc^2x$, $D\csc x=-\csc x\cot x$, on their domains; then apply the chain rule.',
    r'Differentiate $\tan(4x)$, including its domain restriction.',
    r'$4\sec^2(4x)$ where $\cos(4x)\ne0$.',
    r'Differentiate $\sec(x^2)$ and derive $D\tan x$ from sine/cosine using the quotient rule.',
    r'$2x\sec(x^2)\tan(x^2)$. The quotient derivative of sine/cosine is $(\cos^2x+\sin^2x)/\cos^2x=\sec^2x$.',
    r'$D\tan x=\sec x\tan x$.',
    r'That is the derivative of secant; derive tangent’s $\sec^2x$ from its quotient to distinguish them.')
add('u2-derivatives-of-inverse-trigonometric-functions',
    r'$D\arcsin u=u^{\prime}/\sqrt{1-u^2}$ for $|u|<1$ and $D\arctan u=u^{\prime}/(1+u^2)$. Principal branches and endpoints matter.',
    r'Differentiate $\arctan(2x)$ and give its domain.',
    r'$2/(1+4x^2)$ for all real inputs.',
    r'Differentiate $\arcsin(3x)$ and state where the derivative is finite.',
    r'$3/\sqrt{1-9x^2}$ for $|x|<1/3$. The original function includes endpoints, but its derivative is unbounded there.',
    r'$\sin^{-1}x$ means $1/\sin x$ in inverse-function notation.',
    r'Here it means arcsine, the principal inverse of restricted sine; the reciprocal is cosecant.')
add('u2-graphical-differentiability',
    r'A finite tangent slope requires matching finite one-sided secant-slope limits. Corners, cusps, vertical tangents and discontinuities need separate explanations; continuity is necessary but insufficient.',
    r'For the graph $y=|x-2|$, compare secant slopes from $(2,0)$ to points on its left and right. Is there a derivative at 2?',
    r'Left slopes -1 and right slopes 1; the corner has no common slope although the graph is continuous.',
    r'Compare the graphs $y=x^2$ and $y=\sqrt[3]{x}$ at zero. Which has a finite derivative?',
    r'$x^2$ has derivative zero. Cube-root secant slopes are $1/x^{2/3}$ for nonzero $x$, unbounded positively, so no finite derivative.',
    r'A continuous graph is always differentiable.',
    r'A corner such as $|x-2|$ is continuous but has unequal one-sided slopes.')
add('u2-analytic-differentiability',
    r'At a piecewise join, first check continuity, then compare one-sided derivatives through valid difference quotients. Matching branch derivative formulas alone cannot repair a jump.',
    r'Let $f(x)=x^2$ for $x\le1$ and $f(x)=ax+b$ for $x>1$. Choose $a,b$ for differentiability at 1.',
    r'Continuity gives $a+b=1$; matching slopes gives $a=2$, hence $b=-1$. Both conditions are necessary.',
    r'Let $g(x)=x^2$ for $x<0$ and $g(x)=x^2+1$ for $x\ge0$. Branch derivatives both approach zero. Is $g$ differentiable at zero?',
    r'No. It is discontinuous there: left limit 0, value/right limit 1. Differentiability would imply continuity.',
    r'Equal derivatives of the two branch formulas guarantee differentiability at the join.',
    r'Continuity and the difference quotient using the actual point value must also hold; the second function is a counterexample.')
add('u2-derivative-theorems',
    r'MVT requires continuity on $[a,b]$ and differentiability on $(a,b)$; it guarantees an interior tangent slope equal to the secant slope. Rolle additionally requires equal endpoint values.',
    r'For $f(x)=x^2$ on $[1,3]$, check MVT hypotheses and find all qualifying $c$.',
    r'The polynomial satisfies both hypotheses. Secant slope 4 equals $2c$, giving $c=2$ inside the interval.',
    r'Why does Rolle not guarantee a zero derivative for $f(x)=|x|$ on $[-1,1]$, despite equal endpoint values?',
    r'It is not differentiable at the interior corner zero; the differentiability hypothesis fails.',
    r'Equal endpoint values are enough for Rolle’s theorem.',
    r'Continuity on the closed interval and differentiability throughout the interior are also required.')

add('u3-tangent-lines-and-normal-lines',
    r'Tangent slopes come from derivatives. A normal is perpendicular: its slope is the negative reciprocal of a nonzero finite tangent slope. A horizontal tangent has a vertical normal.',
    r'Find the tangent and normal lines to $y=x^2$ at $(1,1)$.',
    r'Tangent $y-1=2(x-1)$; normal $y-1=-\tfrac12(x-1)$. Both pass through the point.',
    r'Find the normal line to $y=x^2$ at zero. Explain why the usual slope formula cannot be used directly.',
    r'The tangent is horizontal with slope zero; its perpendicular normal is the vertical line $x=0$, whose slope is undefined.',
    r'Normal slope is the reciprocal of tangent slope.',
    r'It is the negative reciprocal when defined, because perpendicular finite slopes multiply to -1.')
add('u3-linear-approximations',
    r'$L(x)=f(a)+f^{\prime}(a)(x-a)$ approximates a differentiable function locally. Concavity determines the tangent’s above/below relationship when it holds throughout the relevant neighborhood.',
    r'Use the tangent at $x=4$ to approximate $\sqrt{4.1}$.',
    r'$2+(1/4)(0.1)=2.025$. The concave-down square root lies below its tangent, so this overestimates.',
    r'Use $a=0$ to approximate $e^{-0.03}$. Explain the expected error direction.',
    r'$1-0.03=0.97$; exponential is concave up, so its tangent underestimates the exact value.',
    r'Linear approximation is exact for all inputs.',
    r'It is local and generally approximate; only an affine function agrees with its tangent everywhere on an interval.')
add('u3-critical-points',
    r'Interior domain points where the derivative is zero or does not exist are critical numbers under the usual class convention. Classify only after testing; excluded domain points are not critical numbers.',
    r'Find all critical numbers of $f(x)=x^3-3x$.',
    r'$f^{\prime}=3x^2-3=0$ at $x=-1,1$; the derivative exists everywhere.',
    r'Compare critical numbers of $|x|$ and $1/x$. Explain the domain distinction at zero.',
    r'$|x|$ has critical number zero because it is defined there and lacks a derivative. $1/x$ excludes zero and has no critical numbers.',
    r'Every zero of a denominator is a critical number.',
    r'The point must belong to the original domain; a vertical asymptote’s excluded input is not a critical number.')
add('u3-monotonicity',
    r'Derivative sign on an interval controls increasing/decreasing behavior; a zero derivative at one isolated point does not decide either direction.',
    r'Find increasing and decreasing intervals for $f(x)=x^3-3x$. Show a derivative sign chart.',
    r'$f^{\prime}=3(x-1)(x+1)$ is positive outside $[-1,1]$ and negative inside: increasing on $(-\infty,-1),(1,\infty)$, decreasing on $(-1,1)$.',
    r'Given $f^{\prime}(x)=x^2$, does the function change from decreasing to increasing at zero?',
    r'No. The derivative is positive on either side and zero only at zero; the function increases through zero.',
    r'$f^{\prime}(a)=0$ means the function is constant near $a$.',
    r'A single zero slope is insufficient. A derivative identically zero on an interval, under differentiability hypotheses, implies constancy there.')
add('u3-first-derivative-test',
    r'A positive-to-negative derivative sign change gives a local maximum; negative-to-positive gives a local minimum. A stationary point with no sign change need not be an extremum.',
    r'Classify the critical points of $f(x)=x^3-3x$ using the first derivative test.',
    r'At -1 the sign changes + to -, giving local maximum $f(-1)=2$; at 1 it changes - to +, giving local minimum $f(1)=-2$.',
    r'Classify the critical point of $g(x)=x^3$ at zero by a sign test.',
    r'$g^{\prime}=3x^2$ is positive on both sides, so zero is neither a local maximum nor minimum.',
    r'A zero derivative always gives a local extremum.',
    r'Test signs; $x^3$ has zero derivative at zero and no extremum.')
add('u3-concavity-and-inflection-points',
    r'Concavity describes how slopes change: $f^{\prime\prime}>0$ means concave up and $f^{\prime\prime}<0$ means concave down. An inflection requires a genuine concavity change at an appropriate point of the graph.',
    r'Find concavity intervals and inflection points for $f(x)=x^3-3x$.',
    r'$f^{\prime\prime}=6x$: concave down for $x<0$, up for $x>0$; the inflection point is $(0,0)$.',
    r'Does $g(x)=x^4$ have an inflection at zero because $g^{\prime\prime}(0)=0$?',
    r'No: $g^{\prime\prime}=12x^2$ is positive on both sides, so concavity does not change.',
    r'Every zero of the second derivative is an inflection point.',
    r'It is only a candidate; check both neighboring concavities and the function’s domain/point behavior.')
add('u3-second-derivative-test',
    r'At a stationary point, a positive second derivative gives a local minimum and a negative second derivative gives a local maximum under the usual smoothness hypotheses. Zero makes the test inconclusive.',
    r'Use the second derivative test at the critical numbers of $f(x)=x^3-3x$.',
    r'$f^{\prime}=3x^2-3$, $f^{\prime\prime}=6x$. At -1 the second derivative is -6, giving a local maximum; at 1 it is 6, giving a local minimum.',
    r'Apply the test to $x^4$ and $x^3$ at zero, then use another method to decide.',
    r'Both second derivatives vanish there, so the test is inconclusive. $x^4$ has a minimum by its nonnegative values; $x^3$ has no extremum by derivative sign.',
    r'$f^{\prime\prime}(a)=0$ proves there is no extremum.',
    r'It supplies no decision; $x^4$ at zero disproves the claim.')
add('u3-candidates-test',
    r'A continuous function on a closed bounded interval attains absolute extrema. Compare values at all interior critical numbers and both endpoints, including nondifferentiable interior points.',
    r'Find absolute extrema of $f(x)=x^3-3x$ on $[-2,2]$ by listing candidates and values.',
    r'Candidates -2,-1,1,2 have values -2,2,-2,2. Absolute maximum 2 at -1 and 2; minimum -2 at -2 and 1.',
    r'Find absolute extrema of $|x-1|$ on $[0,3]$. Include the nondifferentiable candidate.',
    r'Values at 0,1,3 are 1,0,2. Minimum 0 at 1; maximum 2 at 3.',
    r'Only points where $f^{\prime}=0$ need checking.',
    r'Endpoints and interior domain points without a derivative also matter; otherwise either displayed problem can lose an extremum.')
add('u3-function-analysis-with-graphs',
    r'Read derivative graphs to obtain function trends: the sign of $f^{\prime}$ controls monotonicity; whether $f^{\prime}$ rises or falls controls concavity. Function heights need a starting value or accumulation.',
    r'A graph of $f^{\prime}$ is above the axis on $(-2,0)$ and below it on $(0,2)$, crossing at zero. What happens to $f$ at zero?',
    r'$f$ increases then decreases, so it has a local maximum at zero; its height is not determined by this sign information.',
    r'On $(1,3)$, $f^{\prime}$ is negative but increasing. Is $f$ increasing? What is its concavity?',
    r'$f$ is decreasing because $f^{\prime}<0$, and concave up because its slopes are increasing.',
    r'An increasing derivative graph means the original function is increasing.',
    r'It means slopes increase, which signals concavity; the sign of the derivative decides original monotonicity.')
add('u3-sketching-curves',
    r'Combine domain, intercepts, symmetry, derivative sign, concavity and end/asymptotic behavior. A sketch must make all constraints consistent; do not treat a hole as an asymptote.',
    r'Sketch $f(x)=x^3-3x$ using intercepts, critical points and inflection behavior.',
    r'Intercepts $-\sqrt3,0,\sqrt3$; local maximum $(-1,2)$, minimum $(1,-2)$; inflection $(0,0)$; decreasing between critical numbers and concave down left/up right of zero.',
    r'For $g(x)=1/x$, describe its domain, asymptotes and monotonicity on each branch. Is there a local minimum at zero?',
    r'Domain excludes zero; vertical $x=0$ and horizontal $y=0$; derivative $-1/x^2<0$ on each branch. Zero is outside the graph, not a minimum.',
    r'The shape of a curve is determined by its critical points alone.',
    r'Domain, derivative signs, concavity and end behavior supply additional necessary constraints; critical points alone omit asymptotes and holes.')
add('u3-lhopitals-rule-quotients',
    r'L’Hôpital requires a qualifying $0/0$ or $\infty/\infty$ quotient, differentiability on a punctured interval and the theorem’s derivative-ratio hypotheses. It replaces the quotient with a ratio of derivatives, not the derivative of the quotient.',
    r'Evaluate $\lim_{x\to0}(e^x-1)/x$ using L’Hôpital, checking its form first.',
    r'$0/0$ applies; derivative ratio $e^x/1\to1$, so the limit is 1.',
    r'Can L’Hôpital be applied directly to $\lim_{x\to0}(x+2)/(x+1)$? Evaluate correctly.',
    r'No, its form is $2/1$, not indeterminate. Continuity gives 2; differentiating numerator and denominator would incorrectly give 1.',
    r'L’Hôpital differentiates the original quotient using the quotient rule.',
    r'It compares separate numerator and denominator derivatives under special limit hypotheses; quotient-rule differentiation is a different operation.')
add('u3-lhopitals-rule-products',
    r'A product of a vanishing and unbounded factor is indeterminate. Rewrite as a quotient and check a qualifying form before considering L’Hôpital; preserve the approach domain.',
    r'Find $\lim_{x\to0^+}x\ln x$ by converting it to a quotient.',
    r'$\ln x/(1/x)$ has the appropriate infinite form; derivative ratio $(1/x)/(-1/x^2)=-x\to0$. The limit is 0, approached from below.',
    r'Find $\lim_{x\to\infty}x e^{-x}$ using an appropriate quotient.',
    r'$x/e^x$ is $\infty/\infty$; derivative ratio $1/e^x\to0$.',
    r'For an indeterminate product, differentiate both factors and multiply.',
    r'There is no such L’Hôpital product rule. Rewrite to a valid quotient; differentiating factors blindly can change the limit.')

add('u4-position-velocity-acceleration-and-speed',
    r'$v=s^{\prime}$, $a=v^{\prime}=s^{\prime\prime}$, and speed is $|v|$. Position, signed velocity, acceleration and speed have different meanings and units.',
    r'For $s(t)=t^3-6t^2+9t$ meters, find position, velocity, acceleration and speed at $t=2$ seconds.',
    r'$s(2)=2$ m; $v=3t^2-12t+9$ gives -3 m/s; $a=6t-12$ gives 0 m/s²; speed is 3 m/s.',
    r'At an instant $v=-4$ m/s and $a=2$ m/s². What is the direction of motion, speed and instantaneous rate of change of speed?',
    r'Moving in the negative direction, speed 4 m/s, speed derivative -2 m/s² because for negative velocity $|v|=-v$.',
    r'Negative velocity means negative speed.',
    r'Speed is the magnitude $|v|\ge0$; negative velocity specifies direction.')
add('u4-speeding-up-and-slowing-down',
    r'For nonzero velocity, speed increases when velocity and acceleration have the same sign and decreases when they have opposite signs. At zero velocity, examine neighboring behavior.',
    r'Let $v(t)=t^2-4$ for $t>0$. Determine when the particle speeds up and slows down.',
    r'$a=2t>0$. On $(0,2)$ velocity is negative, so slowing down; on $(2,\infty)$ it is positive, so speeding up. At 2 speed is zero and the neighboring behaviors differ.',
    r'Compare $(v,a)=(-3,-2)$ and $(3,-2)$ with units m/s and m/s². Explain each speed trend.',
    r'The first speeds up: negative motion becomes more negative. The second slows down: positive velocity decreases toward zero.',
    r'Negative acceleration always means slowing down.',
    r'It can increase speed during negative motion. Check both velocity and acceleration signs.')
add('u4-graphs-of-linear-particle-motion',
    r'On a velocity-time graph, signed area gives displacement and slope gives acceleration. Axis crossings may mark direction changes; absolute area gives traveled distance.',
    r'A velocity graph is the line $v(t)=2-t$ on $[0,4]$. Find direction-change time, acceleration and signed displacement.',
    r'Direction changes at 2; acceleration is -1 throughout; the two equal opposite triangular areas give displacement 0.',
    r'For the same graph, find total distance and explain why it differs from displacement.',
    r'Total distance is $2+2=4$ units of length; negative velocity contributes positive traveled length.',
    r'Area below the velocity axis represents negative traveled distance.',
    r'It is negative displacement. Distance counts absolute area and cannot be negative.')
add('u4-rates-of-change',
    r'An average rate is a signed change divided by an input interval. An instantaneous rate is a derivative, with output-per-input units and a specific evaluation time.',
    r'Water height is $h(t)=5+2t+t^2$ cm, with $t$ in minutes. Find the average rate on $[1,3]$ and instantaneous rate at 1.',
    r'$h(1)=8,h(3)=20$, so average 6 cm/min; $h^{\prime}(1)=4$ cm/min.',
    r'Temperature has $T(5)=18$ °C and $T^{\prime}(5)=-0.4$ °C/min. Estimate $T(5.2)$ and state the approximation used.',
    r'$18-0.4(0.2)=17.92$ °C by local linear approximation; a derivative is a local rate, not a guarantee of constant future rate.',
    r'$T^{\prime}(5)=-0.4$ means the temperature is -0.4 °C.',
    r'It is the local change per minute; the temperature itself is the distinct value $T(5)=18$ °C.')
add('u4-solving-related-rates',
    r'Choose variables and a geometric constraint, differentiate with respect to time while variables still vary, then substitute the instantaneous values. Signed rates and dimensions matter.',
    r'A circle has radius 3 cm growing at 2 cm/s. Find its area growth rate.',
    r'$A=\pi r^2$, so $dA/dt=2\pi r\,dr/dt=12\pi$ cm²/s.',
    r'A 5 m ladder has foot distance $x=3$ m increasing at 0.2 m/s. Find the top height’s rate at that instant.',
    r'From $x^2+y^2=25$, $y=4$ m and $2x x^{\prime}+2y y^{\prime}=0$, hence $y^{\prime}=-0.15$ m/s.',
    r'Substitute the instantaneous radius into $A=\pi r^2$ before differentiating.',
    r'That converts a changing relationship into a constant and loses the rate; differentiate first, then evaluate.')
add('u4-optimizing-functions',
    r'Specify the admissible domain, locate all valid candidates and prove a global comparison, including endpoints or limiting behavior. A stationary point alone is insufficient.',
    r'Find the maximum of $f(x)=12x-x^2$ on $[0,10]$, showing all candidate values.',
    r'$f^{\prime}=12-2x$ gives $x=6$ with value 36; endpoints give 0 and 20. The maximum is 36 at 6.',
    r'Does $g(x)=x^3$ have a minimum on all real inputs because its derivative vanishes at zero?',
    r'No: it is increasing through zero and unbounded below; the stationary point is not an extremum.',
    r'Finding $f^{\prime}=0$ completes an optimization proof.',
    r'You must verify domain feasibility, check all candidates/endpoints and establish the requested global extremum.')
add('u4-optimizing-functions-in-context',
    r'Construct an objective and constraint from the context, reduce variables, impose the physical domain and interpret the proven optimum with units.',
    r'A rectangle has perimeter 20 m. Maximize its area by choosing side $x$ and stating its feasible domain.',
    r'Other side $10-x$ with $0<x<10$; $A=x(10-x)$ has maximum 25 m² at $x=5$. The derivative changes + to -; endpoint-degenerate limits are zero.',
    r'You have 24 m of fence for three sides of a rectangular pen against a wall. Find dimensions maximizing area.',
    r'Two perpendicular sides $x$, parallel side $24-2x$, domain $0<x<12$. Area $24x-2x^2$ peaks at $x=6$, parallel side 12, area 72 m².',
    r'Every fixed-perimeter problem is optimized by a square.',
    r'The physical constraint matters: three fenced sides against a wall give a 6-by-12 rectangle, not a square.')

add('u5-riemann-sums',
    r'Partition an input interval and sum sample heights times widths: $\sum f(x_i^*)\Delta x_i$. Left, right and midpoint refer to sample choices; nonuniform widths remain distinct.',
    r'For $f(x)=x^2$ on $[0,2]$ with two equal subintervals, find left and right sums.',
    r'Widths are 1. Left $0^2+1^2=1$; right $1^2+2^2=5$. Since the function increases, these underestimate/overestimate the integral respectively.',
    r'A table gives times $0,1,3$ and rates $2,4,5$ liters/minute. Find left and right sums over $[0,3]$.',
    r'Left $2(1)+4(2)=10$ L; right $4(1)+5(2)=14$ L. The second interval width is 2, not 1. Without between-sample monotonicity, error direction is not established.',
    r'Every table-based sum uses one common width.',
    r'Only equally spaced partitions do. Keep each actual interval width with its sample rate.')
add('u5-trapezoid-rule',
    r'On each subinterval, trapezoidal area is width times the average of its endpoint heights. For equal widths it averages left and right sums. Error direction requires concavity information, not mere sample values.',
    r'Approximate $\int_0^2x^2\,dx$ using trapezoids of width 1. Predict the error direction.',
    r'$\tfrac12(0+1)+\tfrac12(1+4)=3$. The integrand is concave up, so the connecting chords lie above the curve; it overestimates $8/3$.',
    r'A rate table has times $0,2,5$ and rates $1,3,7$ L/min. Compute the trapezoidal accumulated amount.',
    r'$2(1+3)/2+3(3+7)/2=19$ L. Use the distinct widths 2 and 3.',
    r'Trapezoids always give the exact integral of a curved function.',
    r'They are exact for an affine integrand on each interval, but generally approximate curved graphs.')
add('u5-limit-definition-of-riemann-integrals',
    r'A definite Riemann integral is the limit of sums as the maximum subinterval width tends to zero when that common limit exists. It is signed accumulation, not necessarily positive geometric area.',
    r'Express $\int_0^3x^2\,dx$ as a limit of equal-width right-endpoint sums; identify widths and samples.',
    r'$\lim_{n\to\infty}\sum_{i=1}^n(3i/n)^2(3/n)$; width $3/n$, right sample $3i/n$.',
    r'Identify the definite integral represented by $\lim_{n\to\infty}\sum_{i=1}^n[2+4i/n]^3(4/n)$.',
    r'$\int_2^6x^3\,dx$: interval starts at 2, width total 4 and the sample expression is $x_i^3$.',
    r'Increasing the number of intervals always proves convergence, regardless of widths.',
    r'The mesh must shrink; adding tiny intervals elsewhere while retaining one large interval is insufficient.')
add('u5-geometric-evaluation-of-riemann-integrals',
    r'Use signed geometric areas: positive above the axis and negative below. Known rectangles, triangles and semicircles can evaluate integrals without an antiderivative.',
    r'Evaluate $\int_{-1}^1x\,dx$ and distinguish it from the geometric area between the graph and the axis.',
    r'The signed triangles cancel, giving 0; their total geometric area is 1.',
    r'Evaluate $\int_{-2}^2\sqrt{4-x^2}\,dx$ using geometry.',
    r'The graph is the upper semicircle of radius 2, so the integral is $\tfrac12\pi(2^2)=2\pi$.',
    r'A definite integral is always nonnegative because it is area.',
    r'It is signed accumulation. For example $\int_0^1(-2)\,dx=-2$.')
add('u5-integration-with-respect-to-y',
    r'When integrating in $y$, horizontal slices have thickness $dy$, bounds are output coordinates and horizontal lengths are right-minus-left functions of $y$.',
    r'The region has $0\le y\le4$ and $0\le x\le\sqrt y$. Set up and evaluate its area using $dy$.',
    r'$\int_0^4\sqrt y\,dy=[(2/3)y^{3/2}]_0^4=16/3$. The slice length is $\sqrt y$.',
    r'For the region between $x=y^2$ and $x=4$ with $-2\le y\le2$, write the horizontal-slice area integral.',
    r'$\int_{-2}^2(4-y^2)\,dy=32/3$, right minus left.',
    r'Changing $dx$ to $dy$ leaves the integrand and bounds unchanged.',
    r'Change the slicing variable, its geometric lengths and its coordinate bounds consistently.')
add('u5-properties-of-riemann-integrals',
    r'Integrals are linear, reverse sign when bounds reverse and add over adjacent intervals. Equal bounds give zero. Signed integrals do not generally equal absolute area.',
    r'Given $\int_1^3 f=5$ and $\int_3^6 f=-2$, find $\int_1^6 f$ and $\int_6^1 f$.',
    r'3 by interval additivity, and -3 by reversing bounds.',
    r'If $\int_0^2f=4$ and $\int_0^2g=-1$, find $\int_0^2(3f-2g+5)$.',
    r'$3(4)-2(-1)+5(2)=24$. The constant contributes height times interval length.',
    r'$\int_a^b|f|=|\int_a^bf|$ for every integrable function.',
    r'Cancellation breaks this equality: for $f=x$ on $[-1,1]$ the two sides are 1 and 0.')
add('u5-fundamental-theorem-of-calculus-part-1',
    r'Derivative-of-accumulation direction: for continuous $f$, $A(x)=\int_a^xf(t)\,dt$ has $A^{\prime}(x)=f(x)$. A moving endpoint requires its chain factor. Resolve Armstrong’s part labels from actual notes; this follows OpenStax’s convention.',
    r'For $A(x)=\int_1^x(t^2+2)\,dt$, find $A^{\prime}(3)$ and explain why you need not evaluate the integral.',
    r'$A^{\prime}(x)=x^2+2$ by continuous integrand and FTC, so $A^{\prime}(3)=11$.',
    r'Differentiate $B(x)=\int_0^{x^2}\cos t\,dt$.',
    r'$B^{\prime}(x)=2x\cos(x^2)$ by FTC followed by the chain rule.',
    r'A moving upper limit can be substituted without differentiating it.',
    r'The chain rule multiplies by the upper limit’s derivative; otherwise the second problem loses $2x$.')
add('u5-fundamental-theorem-of-calculus-part-2',
    r'Endpoint-evaluation direction: for continuous $f$ and an antiderivative $F$, $\int_a^bf=F(b)-F(a)$. Verify $F^{\prime}=f$ and domain hypotheses; source part-number conventions may differ.',
    r'Evaluate $\int_1^3(2x+1)\,dx$, verifying the antiderivative.',
    r'$F=x^2+x$ differentiates to $2x+1$; $F(3)-F(1)=12-2=10$.',
    r'Can you evaluate $\int_{-1}^1x^{-2}\,dx$ by $[-1/x]_{-1}^1$ as an ordinary definite integral?',
    r'No. The integrand is undefined and unbounded at zero; the continuous-integrand interval hypothesis fails. Do not use the endpoint expression across the singularity.',
    r'Any antiderivative formula permits endpoint subtraction across every interval.',
    r'The interval’s domain and integrability assumptions matter; a singularity can invalidate routine endpoint evaluation.')
add('u5-corollaries-of-the-fundamental-theorem-of-calculus',
    r'With continuous integrand, differentiating two moving bounds yields $f(b(x))b^{\prime}(x)-f(a(x))a^{\prime}(x)$. Derive this by splitting at a fixed base and orienting the lower interval.',
    r'Differentiate $H(x)=\int_x^{2x}t^2\,dt$.',
    r'$(2x)^2(2)-x^2(1)=7x^2$. The lower-bound contribution is subtracted.',
    r'Differentiate $J(x)=\int_{x^2}^{3x}\sin t\,dt$.',
    r'$3\sin(3x)-2x\sin(x^2)$, with both endpoint chain factors.',
    r'Only the upper endpoint contributes to the derivative of an integral.',
    r'A changing lower endpoint removes accumulated quantity too; subtract its integrand value times its rate.')
add('u5-power-rule-for-antiderivatives',
    r'$\int x^n\,dx=x^{n+1}/(n+1)+C$ for $n\ne-1$ on a valid interval. The exceptional reciprocal case gives $\ln|x|+C$. Verify by differentiation.',
    r'Find all antiderivatives of $3x^2+4x^{-2}$ on $x>0$.',
    r'$x^3-4x^{-1}+C$; differentiating recovers the integrand.',
    r'Find an antiderivative of $1/x$ on each connected interval avoiding zero. Why not use the ordinary power formula?',
    r'$\ln|x|+C$ on either sign interval. With exponent -1 the power formula divides by zero, so it does not apply.',
    r'The power antiderivative rule includes exponent -1.',
    r'It explicitly excludes -1; the logarithmic formula is verified separately.')
add('u5-deriving-ln-x',
    r'Define $L(x)=\int_1^xdt/t$ for $x>0$. FTC gives $L^{\prime}=1/x$, and substitution explains $L(ab)=L(a)+L(b)$, connecting accumulation to natural logarithms.',
    r'For $L(x)=\int_1^xdt/t$, find $L(1)$, $L^{\prime}(2)$ and the sign of $L(1/2)$.',
    r'0, $1/2$, and negative: positive integrand with reversed bounds gives a negative integral.',
    r'Use $t=au$ to show $\int_a^{ab}dt/t=\int_1^bdu/u$ for $a,b>0$. Explain the product-log connection.',
    r'$dt=a\,du$ cancels the $a$ in $t=au$, and bounds become 1 and $b$; additivity gives $L(ab)=L(a)+L(b)$.',
    r'$\int_1^xdt/t$ defines a real logarithm for negative $x$ by the same ordinary integral.',
    r'Crossing zero encounters an undefined singular integrand. This definition’s domain is positive inputs.')
add('u5-antiderivatives-of-exponential-and-logarithmic-functions',
    r'For constant $k\ne0$, $\int e^{kx}dx=e^{kx}/k+C$; $\int a^x dx=a^x/\ln a+C$ for $a>0,a\ne1$. Reciprocal patterns give $\ln|u|$ only with the needed derivative factor.',
    r'Find and verify an antiderivative of $e^{2x}+3^x$.',
    r'$\tfrac12e^{2x}+3^x/\ln3+C$, whose derivative recovers both terms.',
    r'Find $\int 2x/(x^2+5)\,dx$, explaining the logarithmic pattern.',
    r'$\ln(x^2+5)+C$ because the numerator is the derivative of the positive denominator.',
    r'$\int\ln x\,dx=1/x+C$ because logarithms and reciprocals are related.',
    r'$1/x$ is the derivative of $\ln x$, not its antiderivative. Integrating $\ln x$ is a different problem and may require an out-of-scope method.')
add('u5-antiderivatives-of-sinee-and-cosine',
    r'Reverse the verified identities: $\int\sin(kx)dx=-\cos(kx)/k+C$ and $\int\cos(kx)dx=\sin(kx)/k+C$ for constant nonzero $k$.',
    r'Find an antiderivative of $\sin(3x)+2\cos(2x)$.',
    r'$-\tfrac13\cos(3x)+\sin(2x)+C$. Differentiation checks both the signs and factors.',
    r'Evaluate $\int_0^{\pi/2}\cos x\,dx$ and verify its sign geometrically.',
    r'$[\sin x]_0^{\pi/2}=1$. The integrand is nonnegative throughout this interval.',
    r'An antiderivative of $\sin x$ is $\cos x$.',
    r'It is $-\cos x$ because the derivative of positive cosine is negative sine.')
add('u5-antiderivatives-involving-inverse-trigonometric-functions',
    r'Recognize $1/(1+x^2)$ as the derivative of arctangent and $1/\sqrt{1-x^2}$ as the derivative of arcsine inside its finite-derivative domain. Scaling requires a verified substitution.',
    r'Find $\int dx/(1+x^2)$ and $\int dx/\sqrt{1-x^2}$. State the second integrand’s real domain.',
    r'$\arctan x+C$ and $\arcsin x+C$ respectively; the second integrand is defined on $(-1,1)$.',
    r'Find $\int dx/(4+x^2)$ and verify its coefficient by differentiation.',
    r'$\tfrac12\arctan(x/2)+C$, whose derivative is $1/(4+x^2)$.',
    r'$\int dx/(4+x^2)=\arctan x+C$.',
    r'The denominator scale changes both the argument and prefactor; differentiate to discover the mismatch.')
add('u5-integrals-with-piecewise-functions-and-absolute-value',
    r'Split the interval at branch changes and zeros controlling absolute value. Integrate each correct expression and keep signed versus absolute accumulation distinct.',
    r'Evaluate $\int_{-1}^2|x|\,dx$ by splitting at zero.',
    r'$\int_{-1}^0(-x)dx+\int_0^2x\,dx=1/2+2=5/2$.',
    r'Let $f(x)=2$ for $x<1$ and $f(x)=x$ for $x\ge1$. Evaluate $\int_0^3 f(x)dx$.',
    r'$\int_0^1 2dx+\int_1^3xdx=2+4=6$. A single endpoint value does not affect the integral.',
    r'$|x|=x$ throughout every integral.',
    r'On negative inputs it equals $-x$; split intervals where the absolute-value argument changes sign.')
add('u5-u-substitution-for-indefinite-integrals',
    r'Reverse the chain rule by choosing $u$ and replacing the entire differential. After integrating in $u$, substitute back and verify by differentiating; constants of integration remain.',
    r'Find $\int 2x(x^2+1)^3dx$, showing $u$ and $du$.',
    r'$u=x^2+1$, $du=2x\,dx$; result $(x^2+1)^4/4+C$.',
    r'Find $\int x\cos(x^2)dx$. Explain the coefficient adjustment.',
    r'With $u=x^2$, $du=2x\,dx$, the result is $\tfrac12\sin(x^2)+C$.',
    r'You can replace an inner expression by $u$ while leaving unrelated $x$ factors unchanged.',
    r'The integral must be entirely expressed in the new variable and differential; a mixed-variable expression is not a completed substitution.')
add('u5-u-substitution-for-definite-integrals',
    r'For definite substitution, convert both endpoints to the new variable and evaluate consistently, or substitute back before using original bounds. Reversed transformed bounds carry their own orientation.',
    r'Evaluate $\int_0^1 2x(x^2+1)^2dx$ using transformed bounds.',
    r'$u=x^2+1$ gives bounds 1 to 2; $\int_1^2u^2du=7/3$.',
    r'Evaluate $\int_0^1 2x e^{-x^2}dx$ with $u=-x^2$, explaining the sign and bounds.',
    r'$du=-2x dx$, bounds 0 to -1; $-\int_0^{-1}e^u du=1-e^{-1}$.',
    r'After changing to $u$, the old $x$ bounds can stay attached to the $u$ antiderivative.',
    r'The bounds must refer to the variable being evaluated. Convert endpoints or return the antiderivative to $x$ first.')
add('u5-more-trigonometric-antiderivatives',
    r'Use verified reverse trig-derivative patterns such as secant-squared and secant-tangent, with inner scaling or a justified substitution. Broader trig integration methods are not automatically required.',
    r'Find $\int\sec^2(2x)dx$ and state an interval restriction.',
    r'$\tfrac12\tan(2x)+C$ on any connected interval avoiding $\cos(2x)=0$.',
    r'Find $\int\sec(3x)\tan(3x)dx$ and verify it.',
    r'$\tfrac13\sec(3x)+C$ on valid intervals; differentiating introduces the compensating factor 3.',
    r'$\int\sec^2(2x)dx=\tan(2x)+C$.',
    r'Differentiating that expression gives twice the integrand; divide by the inner slope 2.')
add('u5-integrals-of-rational-functions',
    r'First inspect whether algebraic division, termwise powers or a logarithmic numerator/denominator-derivative pattern is sufficient. Keep excluded inputs and absolute values; do not assume partial fractions are already class scope.',
    r'Find $\int(x^2+1)/x\,dx$ on a connected interval avoiding zero.',
    r'Rewrite as $x+1/x$; result $x^2/2+\ln|x|+C$.',
    r'Find $\int(2x+3)/(x^2+3x+5)\,dx$ and check the domain.',
    r'$\ln(x^2+3x+5)+C$; numerator is the denominator derivative and the quadratic is always positive.',
    r'Every rational integral is the logarithm of its denominator.',
    r'That requires a matching derivative numerator up to a constant. For $1/x^2$ the antiderivative is $-1/x$, not $\ln(x^2)$.')

add('u6-average-value-of-a-function',
    r'$f_{avg}=\frac1{b-a}\int_a^bf(x)dx$ for an integrable function on a nonzero-length interval. This is an input-weighted mean, not usually the mean of endpoint heights.',
    r'Find the average value of $f(x)=x^2$ on $[0,3]$.',
    r'$\tfrac13[x^3/3]_0^3=3$. Divide accumulated value 9 by interval length 3.',
    r'For the same function, find the interior input whose output equals its average, and state the theorem’s hypothesis.',
    r'$x=\sqrt3$; continuity on the closed interval permits the integral mean-value conclusion.',
    r'Average function value is always $(f(a)+f(b))/2$.',
    r'For $x^2$ on $[0,3]$ that gives $9/2$ instead of the actual 3. Endpoint averaging is not generally valid.')
add('u6-accumulation-model-of-ftc',
    r'An accumulated quantity is initial amount plus an integral of its signed rate. Its derivative recovers a continuous rate; rate zeros and sign changes control its extrema.',
    r'Let $A(x)=5+\int_0^x(2t-4)dt$. Find $A(3)$, $A^{\prime}(x)$ and where $A$ decreases for $x>0$.',
    r'$A(x)=5+x^2-4x$, $A(3)=2$, derivative $2x-4$; decreasing on $(0,2)$.',
    r'For the same accumulation, locate and justify its minimum on $[0,4]$.',
    r'Derivative changes - to + at 2; $A(2)=1$ versus endpoints 5 and 5, so the minimum is 1 at 2.',
    r'If the rate graph is increasing, the accumulated quantity must increase.',
    r'An increasing negative rate gives decreasing but concave-up accumulation; the rate’s sign controls accumulation’s monotonicity.')
add('u6-initial-value-problems',
    r'Integrate the derivative to obtain a family, then use the specified input/output condition to determine the constant. Verify both the derivative and the initial condition.',
    r'Find $y$ if $y^{\prime}=3x^2$ and $y(1)=5$.',
    r'$y=x^3+C$; $1+C=5$ gives $y=x^3+4$.',
    r'Find $y$ if $y^{\prime}=\cos x$ and $y(\pi/2)=3$. Check it.',
    r'$y=\sin x+2$; its derivative is cosine and its specified value is 3.',
    r'An initial-value condition changes the derivative formula itself.',
    r'It selects a member of the antiderivative family; the given derivative remains the same.')
add('u6-analytic-applications-of-integrals',
    r'Interpret the requested quantity before choosing average, net accumulation or an initial-value model. This broad schedule heading is a proposed synthesis; actual teacher subtopic coverage still needs confirmation.',
    r'Let $f(x)=2x+1$ on $[0,2]$. Find its definite integral and its average value; explain the difference.',
    r'Integral $[x^2+x]_0^2=6$; average $6/2=3$. One is accumulated output times input units; the other has output units.',
    r'Given $Q^{\prime}(t)=2t+1$ and $Q(0)=4$, find $Q(2)$. Compare with the integral alone.',
    r'$Q(2)=4+\int_0^2(2t+1)dt=10$; the integral 6 is change, not the final amount.',
    r'Average, change and final amount are three names for the same integral.',
    r'Average divides by interval length, change is the signed rate integral and final amount adds the initial value.')
add('u6-area-between-curves',
    r'Area integrates nonnegative slice length: upper-minus-lower for vertical slices or right-minus-left for horizontal slices. Find intersections and split where ordering changes.',
    r'Find the area between $y=x$ and $y=x^2$ on $[0,1]$.',
    r'$\int_0^1(x-x^2)dx=1/6$ since $x\ge x^2$ on this interval.',
    r'Find the area between $y=x$ and $y=-x$ on $[-1,1]$, explaining the necessary split.',
    r'$\int_{-1}^0(-2x)dx+\int_0^1(2x)dx=2$. The upper curve changes at zero.',
    r'Integrating one fixed curve difference always produces geometric area.',
    r'The difference must be nonnegative or split where ordering changes; otherwise positive and negative regions cancel.')
add('u6-volumes-of-revolution-with-disks',
    r'A slice perpendicular to the rotation axis forms a disk with area $\pi R^2$. Radius is distance to the axis, not automatically the graph’s coordinate height.',
    r'Revolve the region $0\le x\le2$, $0\le y\le x$ about the $x$-axis. Set up and evaluate its volume.',
    r'$R=x$, so $V=\pi\int_0^2x^2dx=8\pi/3$.',
    r'Revolve $0\le y\le4$, $0\le x\le\sqrt y$ about the $y$-axis using disks.',
    r'Horizontal slices have $R=\sqrt y$; $V=\pi\int_0^4y\,dy=8\pi$.',
    r'The disk formula is $\pi R$, integrated along the axis.',
    r'Cross-sectional area is $\pi R^2$; the unsquared radius gives wrong geometry and dimensions.')
add('u6-volumes-of-revolution-with-washers',
    r'A washer has area $\pi(R^2-r^2)$ with outer and inner radii measured from the rotation axis. These are separate disks, not the square of their difference.',
    r'Revolve $x^2\le y\le x$ for $0\le x\le1$ about the $x$-axis. Find the volume.',
    r'$R=x,r=x^2$; $V=\pi\int_0^1(x^2-x^4)dx=2\pi/15$.',
    r'Revolve the same region about $y=2$. Name both radii and set up the volume integral.',
    r'$R=2-x^2,r=2-x$; $V=\pi\int_0^1[(2-x^2)^2-(2-x)^2]dx=8\pi/15$. The lower curve is farther from the elevated axis.',
    r'Washer area equals $\pi(R-r)^2$.',
    r'Subtract inner disk area from outer disk area: $\pi(R^2-r^2)$; squaring the thickness describes a different disk.')
add('u6-volumes-of-solids-with-cross-sections',
    r'Volume is $\int A(x)dx$ or $\int A(y)dy$. Obtain each slice’s area from the specified shape and base length; the region alone does not determine the cross-sectional shape.',
    r'A base lies between $y=0$ and $y=x$ for $0\le x\le2$. Perpendicular cross-sections are squares. Find the volume.',
    r'Square side $x$ gives $A=x^2$ and volume $\int_0^2x^2dx=8/3$.',
    r'Use the same base but equilateral-triangle cross-sections. Find the new volume.',
    r'$A=\sqrt3 x^2/4$, giving volume $2\sqrt3/3$. Same slice length, different area coefficient.',
    r'Every cross-section uses the disk factor $\pi$.',
    r'Use the actual slice shape’s area formula; squares and triangles do not use circular disk area.')
add('u6-position-velocity-acceleration-and-ivps',
    r'From acceleration, integrate to velocity and use its initial value, then integrate to position and use its distinct initial value. Both constants and units are necessary.',
    r'A particle has $a(t)=6t$, $v(0)=2$ and $s(0)=5$. Find velocity and position.',
    r'$v=3t^2+2$, then $s=t^3+2t+5$. Both initial conditions check.',
    r'With constant acceleration -2 m/s², initial velocity 6 m/s and position 1 m, find position at 3 s and the first stop time.',
    r'$v=6-2t$ stops at 3 s; $s=1+6t-t^2$, so $s(3)=10$ m.',
    r'One constant is enough after integrating acceleration twice.',
    r'Two integrations introduce distinct constants, fixed separately by velocity and position information.')
add('u6-displacement-and-distance',
    r'Displacement is $\int v(t)dt$ and traveled distance is $\int|v(t)|dt$. Split at genuine velocity sign changes when calculating absolute accumulation.',
    r'For $v(t)=t-1$ on $[0,3]$, find displacement and distance.',
    r'Displacement $[t^2/2-t]_0^3=3/2$. Distance is $1/2+2=5/2$ after splitting at 1.',
    r'A particle’s displacement is zero on an interval. Must it remain stationary? Give a rate example.',
    r'No: $v(t)=t-1$ on $[0,2]$ gives equal opposite signed areas but distance 1.',
    r'Distance equals absolute displacement in every motion problem.',
    r'They coincide when motion has one sign almost everywhere; a reversal can make distance strictly larger.')
add('u6-average-value-of-a-function-in-context',
    r'Average temperature or concentration retains the original quantity’s units. Average rate is net change divided by elapsed time; mean of sparse samples may not be the time-weighted average.',
    r'Temperature is $T(t)=20+t^2$ °C for $0\le t\le3$ hours. Find its average temperature.',
    r'$\tfrac13\int_0^3(20+t^2)dt=23$ °C; integration accumulates degree-hours then division restores °C.',
    r'Flow is $r(t)=2t+1$ L/min on $[0,4]$. Find average flow and total inflow.',
    r'Total is $[t^2+t]_0^4=20$ L; average is 5 L/min.',
    r'An average flow over four minutes has units of liters.',
    r'It has liters per minute; total inflow, a distinct accumulated quantity, has liters.')
add('u6-accumulation-model-of-ftc-in-context',
    r'Amount at a later time equals initial amount plus inflow minus outflow integrals. Interpret a negative net rate as decreasing amount and enforce a physically meaningful interval.',
    r'A tank starts with 10 L. Inflow is 4 L/min and outflow is $t$ L/min. Find amount at 3 min and its rate then.',
    r'$W(t)=10+4t-t^2/2$; $W(3)=35/2$ L and $W^{\prime}(3)=1$ L/min.',
    r'For the same model on $[0,6]$, find when the amount is greatest and justify using net rate.',
    r'Net rate $4-t$ changes positive to negative at 4; amount there is 18 L versus endpoints 10 and 16, so the maximum occurs at 4 min.',
    r'The tank empties whenever inflow equals outflow.',
    r'Equal rates mean zero instantaneous net change, not zero stored amount; here the tank has 18 L then.')
add('u6-ap-style-frqs-applications-of-integrals',
    r'A multi-part rate problem may request amount, average rate, extrema and an interpretation. Write the setup with units and bounds before evaluating; original supplements are not released AP or Armstrong questions.',
    r'An original tank model has $W(0)=8$ L and $W^{\prime}(t)=6-2t$ L/min on $[0,4]$. Find $W(2)$ and average net rate on $[0,4]$. Show setups.',
    r'$W(2)=8+\int_0^2(6-2t)dt=16$ L; average $\tfrac14\int_0^4(6-2t)dt=2$ L/min.',
    r'For the same model, find the maximum amount on $[0,4]$, giving candidate values and sign reasoning.',
    r'$W=8+6t-t^2$, candidates 0,3,4 have values 8,17,16 L; rate changes + to - at 3, so maximum 17 L.',
    r'A correct decimal answer alone establishes the requested justification.',
    r'The requested reasoning needs the mathematical setup, relevant sign/hypothesis evidence and units; assess against the actual prompt, not a fabricated AP rubric.')

add('u7-constructing-slope-fields-from-differential-equations',
    r'At a point $(x,y)$, draw a short segment with slope given by the equation’s right side. The slope field is a local direction guide, not one solution or a graph of derivative versus input alone.',
    r'For $y^{\prime}=x-y$, compute slopes at $(0,0),(1,0),(0,1),(1,1)$ and describe the corresponding segments.',
    r'0,1,-1,0: horizontal, rising at slope 1, falling at slope -1, horizontal respectively.',
    r'For $y^{\prime}=2y$, how do segment slopes vary along a horizontal row? Where are they horizontal?',
    r'Each row has constant slope $2y$, independent of $x$; horizontal along $y=0$.',
    r'The segment slope depends only on the plotted $x$ coordinate.',
    r'The right side may depend on both coordinates; $x-y$ varies when either input changes.')
add('u7-sketching-specific-solutions-on-slope-fields',
    r'A particular solution curve passes through the initial point and follows the field’s tangent directions. Equilibrium solutions are horizontal curves where the rate is identically zero.',
    r'For $y^{\prime}=y$, sketch the solution through $(0,2)$ qualitatively, then verify $y=2e^x$.',
    r'The curve stays positive and increases, with slopes increasing as height rises; derivative $2e^x$ equals $y$ and the initial value is 2.',
    r'For the same equation, compare the solution through $(0,0)$ and through $(0,-2)$.',
    r'The zero solution is a horizontal equilibrium. $y=-2e^x$ stays negative and decreases; its derivative equals itself.',
    r'Every integral curve in one slope field passes through the initial point.',
    r'The initial condition selects a particular curve from the family; the field itself describes many curves.')
add('u7-determining-differential-equations-from-slope-fields',
    r'Compare candidate equations against several coordinate slopes, zero-slope loci and row/column symmetries. A finite sample can distinguish listed candidates but does not uniquely identify every conceivable equation.',
    r'A field has slopes 0 at $(0,0)$, 1 at $(1,0)$ and -1 at $(0,1)$. Choose among $y^{\prime}=x+y$, $x-y$, and $y$, explaining the tests.',
    r'$x-y$ matches all three. $x+y$ gives +1 at $(0,1)$ and $y$ gives 0 at $(1,0)$, contradicting data.',
    r'A field has constant slopes along rows and horizontal segments exactly at $y=2$. Which fits: $y^{\prime}=y-2$ or $y^{\prime}=x-2$?',
    r'$y-2$ is independent of $x$ and vanishes along the row $y=2$; $x-2$ instead varies along rows and vanishes in a column.',
    r'One slope measurement determines the entire differential equation.',
    r'Many right-hand sides agree at a point; use enough discriminating measurements for the given candidates and state the limit of inference.')
add('u7-verifying-solutions-to-differential-equations',
    r'Compute the proposed derivative and compare it with the equation’s right side after substituting the proposed function. Check the initial value separately and preserve a valid domain.',
    r'Verify whether $y=3e^{2x}$ solves $y^{\prime}=2y$, and identify its value at zero.',
    r'$y^{\prime}=6e^{2x}=2y$, so it solves the equation; $y(0)=3$.',
    r'Does $y=x^2+1$ solve $y^{\prime}=2xy$? Show the substitution rather than judging by appearance.',
    r'No: derivative $2x$ differs from right side $2x(x^2+1)$ except at special points. An identity on an interval is required.',
    r'Matching the equation at one input verifies a solution function.',
    r'The differential equation must hold throughout the proposed solution interval, not at just one point.')
add('u7-separable-differential-equations',
    r'Before dividing by a factor of $y$, retain equilibrium solutions. Separate variables, integrate with valid domains, use initial data and verify the solution on an interval avoiding singularities.',
    r'Solve $y^{\prime}=2xy$ with $y(0)=3$, checking any equilibrium lost by division.',
    r'For nonzero $y$, $\ln|y|=x^2+C$, so $y=3e^{x^2}$. The separate equilibrium $y=0$ solves the equation but not this initial condition.',
    r'Solve $y^{\prime}=y^2$ with $y(0)=1$ and state the maximal interval containing zero.',
    r'$-1/y=x+C$ yields $y=1/(1-x)$; the maximal connected interval containing zero is $(-\infty,1)$. Also $y=0$ is an equilibrium but fails the initial value.',
    r'Dividing by $y$ never removes a solution.',
    r'It removes the possible zero solution; test equilibria in the original equation before division.')
add('u7-super-basic-2nd-order-differential-equations',
    r'For the class’s basic second-order cases, integrate a specified second derivative twice and use two conditions. This does not introduce general linear second-order ODE techniques.',
    r'Solve $y^{\prime\prime}=6x$ with $y^{\prime}(0)=2$ and $y(0)=1$.',
    r'$y^{\prime}=3x^2+2$ and $y=x^3+2x+1$, satisfying both conditions.',
    r'With independent variable $t$, solve $s^{\prime\prime}(t)=-4$ with $s(0)=3$ and $s^{\prime}(0)=5$.',
    r'$s^{\prime}=5-4t$, $s=3+5t-2t^2$ when the independent variable is $t$; two integrations fix separate constants.',
    r'A second-order equation needs just one integration constant.',
    r'Two integrations introduce two independent constants; the two initial data determine them separately.')
add('u7-basic-word-problems',
    r'Translate proportional rate statements into equations with units and sign. Initial data determine amplitude; observed changes determine a rate constant through a logarithm.',
    r'A quantity starts at 100 and grows at a rate proportional to its amount with constant $k=0.2$ per hour. Find the model and amount at 5 h.',
    r'$P^{\prime}=0.2P$, $P=100e^{0.2t}$, so $P(5)=100e$; differentiate and check the initial amount.',
    r'A substance decays from 80 g to 40 g in 3 h under $M^{\prime}=kM$. Find $k$ and a model.',
    r'$e^{3k}=1/2$, so $k=-\ln2/3$ per hour and $M=80e^{-(\ln2)t/3}$.',
    r'Proportional growth has the linear model $P=P_0+kt$.',
    r'That assumes a constant absolute rate. A rate proportional to the changing amount gives the exponential solution.')
add('u7-differential-equations-in-the-real-world',
    r'An approach-to-equilibrium model $T^{\prime}=-k(T-T_{env})$ with $k>0$ predicts exponential reduction in the difference. State modeling assumptions, physical time domain and limits of the prediction.',
    r'An object starts at 90 °C in a 20 °C room with $T^{\prime}=-0.1(T-20)$ per minute. Find $T(t)$ and its long-run prediction.',
    r'$T=20+70e^{-0.1t}$ for physical times $t\ge0$; it tends to 20 °C from above. Verification gives the stated rate and initial temperature.',
    r'With the same room and rate law but initial temperature 10 °C, describe the model’s rate sign and solution.',
    r'$T=20-10e^{-0.1t}$; its derivative is positive, so it warms toward 20 from below.',
    r'A mathematical rate model is guaranteed to remain physically accurate forever.',
    r'The model assumes constant environment and rate law. Changing conditions or physical limits can invalidate its predictions despite correct algebra.')
add('u7-ap-style-frqs-differential-equations',
    r'An original multi-part ODE exercise can connect slope, equilibrium, separation, initial condition and qualitative behavior. Show verification and domain; do not present authored tasks as released AP questions.',
    r'For the original model $y^{\prime}=2-y$, $y(0)=5$, find the initial slope and equilibrium, then solve the initial-value problem.',
    r'Initial slope -3; equilibrium $y=2$. Separating or checking gives $y=2+3e^{-x}$, whose derivative equals $2-y$ and value at zero is 5.',
    r'For this solution on $x\ge0$, determine monotonicity, concavity and whether it reaches the equilibrium at a finite time.',
    r'Derivative $-3e^{-x}<0$ gives decreasing behavior; second derivative $3e^{-x}>0$ gives concave up. It approaches but never equals 2 at a finite input.',
    r'A solution approaching equilibrium must cross it eventually.',
    r'This explicit solution remains strictly above 2 for every finite input; approaching does not imply reaching or crossing.')
